sudo: false

language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - ES_VERSION="7.1.1"

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}-linux-x86_64.tar.gz
  - tar -zxvf elasticsearch-${ES_VERSION}-linux-x86_64.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch -E "discovery.type=single-node" &
  - until curl --silent -XGET --fail http://127.0.0.1:9200; do printf '.'; sleep 1; done
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
